# Generated by Django 4.2.4 on 2023-08-29 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_created_date_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='note',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
