# Generated by Django 4.2.4 on 2023-09-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_orderdetail_user_address_orderdetail_user_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
    ]
