# Generated by Django 4.2.4 on 2023-09-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(default='d', on_delete=django.db.models.deletion.CASCADE, to='account.orderdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='id',
            field=models.CharField(default='A1000000001', max_length=10, primary_key=True, serialize=False),
        ),
    ]
