# Generated by Django 4.2.4 on 2023-09-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_orderitems_order_alter_orderdetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
