# Generated by Django 4.2.4 on 2023-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_orderitems_account_orderdetail_orderitems_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ManyToManyField(to='account.orderdetail'),
        ),
    ]
