# Generated by Django 4.2.4 on 2023-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='note',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
